### ISSUE TITLE
Cache, Capacity, Disk Group to esxi host

### ISSUE THREAD

**Issue by eschek87** [equelin/vsanmetrics#1]
Hi,
great script. I am missing the connection between cache, capacity, disk group and esxi hosts. So if I choose cache-disk in grafana I can only filter by cluster and not by esxi host.
![2018-05-23 12_41_04-grafana - vmware_ vsan disk group performance](https://user-images.githubusercontent.com/22763868/40419763-a9ea0db2-5e86-11e8-881c-204362ab4b72.png)

**Comment by equelin** [comment]
Hello @eschek87 ,

Thanks for your feedback. I'm afraid you're right I forgot to add the hostname's tag for those entity types...

I'm planning to add it in the next couple weeks (unless you could propose some code ?)

Regards,

**Comment by equelin** [comment]
Hello,

The missing hostname tags have been added in the latest release (except for the diskgroup entities, I'm working on it !)

https://github.com/equelin/vsanmetrics/releases/tag/0.2.0

**Comment by eschek87** [comment]
Hi,
thanks for that. But the latest version stops with an error if I run:

python /opt/vsanmetrics/vsanmetrics.py -s <vcs> -u <user@domain.com> -p <password>-c <vsan-cluster> --performance --capacity --skipentitytypes virtual-disk,vscsi,virtual-machine,capacity-disk

Traceback (most recent call last):
  File "/opt/vsanmetrics/vsanmetrics.py", line 527, in <module>
    main()
  File "/opt/vsanmetrics/vsanmetrics.py", line 509, in main
    tags = parseEntityRefId(measurement,metric.entityRefId,uuid,vms,disks)
  File "/opt/vsanmetrics/vsanmetrics.py", line 199, in parseEntityRefId
    tags['hostname'] = disks[entityRefId[1]]
KeyError: '5299cd16-b6ce-d615-a45c-65246e741216'

**Comment by jorioux** [comment]
You must add this argument:

`--skipentitytypes cache-disk,capacity-disk`

**Comment by equelin** [comment]
Hopefully, the latest release will fix this issue...

https://github.com/equelin/vsanmetrics/releases/tag/0.2.1
